### ISSUE TITLE
Basic usage example for python validator

### ISSUE THREAD

**Issue by sappelhoff** [VisLab/HEDToolsArchived#76]
There are some usage cases for the python validator buried in the repo:

https://github.com/VisLab/HEDTools/tree/master/python/hedvalidation/examples

It would be nice to have a very concise and basic usage example in the primary README for python (and probably for the other programming languages as well). This would include installation, and applying the validator to a file that has an HED tag column.

**Comment by VisLab** [comment]
This is a good suggestion.  The usage examples that are buried are for regression testing.  We'll try to do something and get back to you.  (It won't be instantaneous.)

**Comment by sappelhoff** [comment]
Any news on this?

**Comment by VisLab** [comment]
Stefan,
I am traveling.  I will deal with this in another week when I return.
Thanks, Kay

**Comment by sappelhoff** [comment]
I am closing this because the repo is archived. 

But my issue would in principle apply to https://github.com/hed-standard/hed-python

So feel free to re-open there if somebody is interested.

**Comment by VisLab** [comment]
We're working on it. It does apply to hed-standard/hed-python.  We'll move
it up in the queue.  Thanks.....

**Comment by VisLab** [comment]
We opened as issue #23 on hed-python and will address shortly.
